# Generated by Django 3.2.5 on 2021-07-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='All', max_length=100)),
                ('Address', models.CharField(blank=True, max_length=250, null=True)),
                ('Name', models.CharField(max_length=250)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('ID_Field', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Program', models.CharField(blank=True, default='All', max_length=50)),
                ('Country', models.CharField(default='All', max_length=100)),
                ('MinNameScore', models.SmallIntegerField()),
                ('List', models.CharField(default='All', max_length=250)),
            ],
        ),
    ]
